apiVersion: v1
kind: Service
metadata:
  name: customers-svc
  labels:
    app: customers-app
spec:
  type: LoadBalancer 
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: customers-app